[package]
name = "metaphrase"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.38"
glob = "0.3.1"
native-tls = "0.2.12"
serde = "1.0.210"
serde_json = "1.0.128"
sha2 = "0.10.8"
